config/routes.rb
Rails.application.routes.draw do

  
  resources :logros

  resources :viajes

  resources :maps

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :users, :only => [:show]

  match 'users/:id' => 'users#show', via: :get

  get 'welcome/index'

  resources :users

  resources :geofences

  root 'welcome#index'

end

app/models/geofence.rb
class Geofence < ActiveRecord::Base

	reverse_geocoded_by :y_act, :x_act
	after_validation :reverse_geocode, :alarma

end

app/controllers/geofences_controller.rb
class GeofencesController < ApplicationController
  before_action :set_geofence, only: [:show, :edit, :update, :destroy]

  # GET /geofences
  # GET /geofences.json
  def index
    @geofences = Geofence.all
    @hash = Gmaps4rails.build_markers(@geofences) do |geofence, marker|
        marker.lat geofence.x_act
        marker.lng geofence.y_act
    end
  end

  # GET /geofences/1
  # GET /geofences/1.json
  def show
  end

  # GET /geofences/new
  def new
    @geofence = Geofence.new
  end

  # GET /geofences/1/edit
  def edit
  end

  # POST /geofences
  # POST /geofences.json
  def create
    @geofence = Geofence.new(geofence_params)

    respond_to do |format|
      if @geofence.save
        format.html { redirect_to @geofence, notice: 'Geofence was successfully created.' }
        format.json { render :show, status: :created, location: @geofence }
      else
        format.html { render :new }
        format.json { render json: @geofence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /geofences/1
  # PATCH/PUT /geofences/1.json
  def update
    respond_to do |format|
      if @geofence.update(geofence_params)
        format.html { redirect_to @geofence, notice: 'Geofence was successfully updated.' }
        format.json { render :show, status: :ok, location: @geofence }
      else
        format.html { render :edit }
        format.json { render json: @geofence.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /geofences/1
  # DELETE /geofences/1.json
  def destroy
    @geofence.destroy
    respond_to do |format|
      format.html { redirect_to geofences_url, notice: 'Geofence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_geofence
      @geofence = Geofence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def geofence_params
      params.require(:geofence).permit(:user_id, :x_act, :y_act, :x_al, :y_al, :alarm)
    end
end

app/helpers/geofences_helper.rb
module GeofencesHelper
end

app/views/geofences/_form.html.erb
<%= form_for(@geofence) do |f| %>
  <% if @geofence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@geofence.errors.count, "error") %> prohibited this geofence from being saved:</h2>

      <ul>
      <% @geofence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :x_act %><br>
    <%= f.text_field :x_act %>
  </div>
  <div class="field">
    <%= f.label :y_act %><br>
    <%= f.text_field :y_act %>
  </div>
  <div class="field">
    <%= f.label :x_al %><br>
    <%= f.text_field :x_al %>
  </div>
  <div class="field">
    <%= f.label :y_al %><br>
    <%= f.text_field :y_al %>
  </div>
  <div class="field">
    <%= f.label :alarm %><br>
    <%= f.check_box :alarm %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to 'Back', geofence_path %>

app/views/geofences/edit.html.erb
<h1>Editing geofence</h1>

<%= render 'form' %>

<%= link_to 'Show', @geofence %> |
<%= link_to 'Back', geofences_path %>

app/views/geofences/index.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<body>
  <br>
  <br>
  <br>
  <br>

  <div style='width: 820px;'>
    <div id="map" style='width: 900px; height: 500px;'>

    <script type="text/javascript">
    
      handler = Gmaps.build('Google');
        handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
      });

    </script>

    </div>
  </div>
  
</body>

app/views/geofences/new.html.erb
<h1>New geofence</h1>

<%= render 'form' %>

<%= link_to 'Back', geofences_path %>

app/views/geofences/show.html.erb
  <script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<body>
  <br>
  <br>
  <br>
  <div style='width: 820px;'>
    <div id="map" style='width: 1000px; height: 500px;'>

      <% if @geofence.alarm? %>
        <script type="text/javascript">

          handler = Gmaps.build('Google');
          handler.buildMap({ provider: {}, internal: {id: 'map', zoom: 10}}, function(){
            markers = handler.addMarkers([
              {
                "lat": <%=@geofence.x_act %>,
                "lng": <%=@geofence.y_act %>
              }
            ]);
            handler.bounds.extendWith(markers);
            handler.fitMapToBounds();
            }
          );

          setInterval( function(){
            window.location.reload(1)
          }, 10000);
          
        </script>

        
      <% else %>

      ¡Esta bicicleta no ha activado la alarma!

      <span class="logo icon fa-bicycle"></span>
      
      <% end %>

    </div>
  </div>
  <%= social_share_button_tag("SmartBike") %>

</body>