config/routes.rb
Rails.application.routes.draw do

  
  resources :logros

  resources :viajes

  resources :maps

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :users, :only => [:show]

  match 'users/:id' => 'users#show', via: :get

  get 'welcome/index'

  resources :users

  resources :geofences

  root 'welcome#index'

end

app/models/viaje.rb
class Viaje < ActiveRecord::Base
end

app/controllers/viajes_controller.rb
class ViajesController < ApplicationController
  before_action :set_viaje, only: [:show, :edit, :update, :destroy]

  # GET /viajes
  # GET /viajes.json
  def index
    @viajes = Viaje.all
  end

  # GET /viajes/1
  # GET /viajes/1.json
  def show
  end

  # GET /viajes/new
  def new
    @viaje = Viaje.new
  end

  # GET /viajes/1/edit
  def edit
  end

  # POST /viajes
  # POST /viajes.json
  def create
    @viaje = Viaje.new(viaje_params)

    respond_to do |format|
      if @viaje.save
        format.html { redirect_to @viaje, notice: 'Viaje was successfully created.' }
        format.json { render :show, status: :created, location: @viaje }
      else
        format.html { render :new }
        format.json { render json: @viaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /viajes/1
  # PATCH/PUT /viajes/1.json
  def update
    respond_to do |format|
      if @viaje.update(viaje_params)
        format.html { redirect_to @viaje, notice: 'Viaje was successfully updated.' }
        format.json { render :show, status: :ok, location: @viaje }
      else
        format.html { render :edit }
        format.json { render json: @viaje.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /viajes/1
  # DELETE /viajes/1.json
  def destroy
    @viaje.destroy
    respond_to do |format|
      format.html { redirect_to viajes_url, notice: 'Viaje was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_viaje
      @viaje = Viaje.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def viaje_params
      params.require(:viaje).permit(:id_viaje, :user_id, :distancia, :tiempo, :fecha)
    end
end

app/helpers/viajes_helper.rb
module ViajesHelper
end

app/views/viajes/_form.html.erb
<%= form_for(@viaje) do |f| %>
  <% if @viaje.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@viaje.errors.count, "error") %> prohibited this viaje from being saved:</h2>

      <ul>
      <% @viaje.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_viaje %><br>
    <%= f.number_field :id_viaje %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :distancia %><br>
    <%= f.text_field :distancia %>
  </div>
  <div class="field">
    <%= f.label :tiempo %><br>
    <%= f.text_field :tiempo %>
  </div>
  <div class="field">
    <%= f.label :fecha %><br>
    <%= f.date_select :fecha %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/viajes/edit.html.erb
<h1>Editing viaje</h1>

<%= render 'form' %>

<%= link_to 'Show', @viaje %> |
<%= link_to 'Back', viajes_path %>

app/views/viajes/index.html.erb
<h1>Listing viajes</h1>

<table>
  <thead>
    <tr>
      <th>Id viaje</th>
      <th>User</th>
      <th>Distancia</th>
      <th>Tiempo</th>
      <th>Fecha</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @viajes.each do |viaje| %>
      <tr>
        <td><%= viaje.id_viaje %></td>
        <td><%= viaje.user_id %></td>
        <td><%= viaje.distancia %></td>
        <td><%= viaje.tiempo %></td>
        <td><%= viaje.fecha %></td>
        <td><%= link_to 'Show', viaje %></td>
        <td><%= link_to 'Edit', edit_viaje_path(viaje) %></td>
        <td><%= link_to 'Destroy', viaje, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Viaje', new_viaje_path %>

app/views/viajes/new.html.erb
<h1>New viaje</h1>

<%= render 'form' %>

<%= link_to 'Back', viajes_path %>

app/views/viajes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id viaje:</strong>
  <%= @viaje.id_viaje %>
</p>

<p>
  <strong>User:</strong>
  <%= @viaje.user_id %>
</p>

<p>
  <strong>Distancia:</strong>
  <%= @viaje.distancia %>
</p>

<p>
  <strong>Tiempo:</strong>
  <%= @viaje.tiempo %>
</p>

<p>
  <strong>Fecha:</strong>
  <%= @viaje.fecha %>
</p>

<%= link_to 'Edit', edit_viaje_path(@viaje) %> |
<%= link_to 'Back', viajes_path %>