config/routes.rb
Rails.application.routes.draw do

  
  resources :logros

  resources :viajes

  resources :maps

  devise_for :users, :controllers => { :omniauth_callbacks => "callbacks" }

  resources :users, :only => [:show]

  match 'users/:id' => 'users#show', via: :get

  get 'welcome/index'

  resources :users

  resources :geofences

  root 'welcome#index'

end

app/models/logro.rb
class Logro < ActiveRecord::Base
end

app/controllers/logros_controller.rb
class LogrosController < ApplicationController
  before_action :set_logro, only: [:show, :edit, :update, :destroy]

  # GET /logros
  # GET /logros.json
  def index
    @logros = Logro.all
  end

  # GET /logros/1
  # GET /logros/1.json
  def show
  end

  # GET /logros/new
  def new
    @logro = Logro.new
  end

  # GET /logros/1/edit
  def edit
  end

  # POST /logros
  # POST /logros.json
  def create
    @logro = Logro.new(logro_params)

    respond_to do |format|
      if @logro.save
        format.html { redirect_to @logro, notice: 'Logro was successfully created.' }
        format.json { render :show, status: :created, location: @logro }
      else
        format.html { render :new }
        format.json { render json: @logro.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logros/1
  # PATCH/PUT /logros/1.json
  def update
    respond_to do |format|
      if @logro.update(logro_params)
        format.html { redirect_to @logro, notice: 'Logro was successfully updated.' }
        format.json { render :show, status: :ok, location: @logro }
      else
        format.html { render :edit }
        format.json { render json: @logro.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logros/1
  # DELETE /logros/1.json
  def destroy
    @logro.destroy
    respond_to do |format|
      format.html { redirect_to logros_url, notice: 'Logro was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_logro
      @logro = Logro.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def logro_params
      params.require(:logro).permit(:id_logro, :meta, :int_multiuso, :logrado, :nombre, :date_inicial, :date_final)
    end
end

app/helpers/logros_helper.rb
module LogrosHelper
end

app/views/logros/_form.html.erb
<%= form_for(@logro) do |f| %>
  <% if @logro.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@logro.errors.count, "error") %> prohibited this logro from being saved:</h2>

      <ul>
      <% @logro.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id_logro %><br>
    <%= f.number_field :id_logro %>
  </div>
  <div class="field">
    <%= f.label :meta %><br>
    <%= f.text_field :meta %>
  </div>
  <div class="field">
    <%= f.label :int_multiuso %><br>
    <%= f.text_field :int_multiuso %>
  </div>
  <div class="field">
    <%= f.label :logrado %><br>
    <%= f.check_box :logrado %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :date_inicial %><br>
    <%= f.date_select :date_inicial %>
  </div>
  <div class="field">
    <%= f.label :date_final %><br>
    <%= f.date_select :date_final %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logros/edit.html.erb
<h1>Editing logro</h1>

<%= render 'form' %>

<%= link_to 'Show', @logro %> |
<%= link_to 'Back', logros_path %>

app/views/logros/index.html.erb
<h1>Listing logros</h1>

<table>
  <thead>
    <tr>
      <th>Id logro</th>
      <th>Meta</th>
      <th>Int multiuso</th>
      <th>Logrado</th>
      <th>Nombre</th>
      <th>Date inicial</th>
      <th>Date final</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logros.each do |logro| %>
      <tr>
        <td><%= logro.id_logro %></td>
        <td><%= logro.meta %></td>
        <td><%= logro.int_multiuso %></td>
        <td><%= logro.logrado %></td>
        <td><%= logro.nombre %></td>
        <td><%= logro.date_inicial %></td>
        <td><%= logro.date_final %></td>
        <td><%= link_to 'Show', logro %></td>
        <td><%= link_to 'Edit', edit_logro_path(logro) %></td>
        <td><%= link_to 'Destroy', logro, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Logro', new_logro_path %>

app/views/logros/new.html.erb
<h1>New logro</h1>

<%= render 'form' %>

<%= link_to 'Back', logros_path %>

app/views/logros/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id logro:</strong>
  <%= @logro.id_logro %>
</p>

<p>
  <strong>Meta:</strong>
  <%= @logro.meta %>
</p>

<p>
  <strong>Int multiuso:</strong>
  <%= @logro.int_multiuso %>
</p>

<p>
  <strong>Logrado:</strong>
  <%= @logro.logrado %>
</p>

<p>
  <strong>Nombre:</strong>
  <%= @logro.nombre %>
</p>

<p>
  <strong>Date inicial:</strong>
  <%= @logro.date_inicial %>
</p>

<p>
  <strong>Date final:</strong>
  <%= @logro.date_final %>
</p>

<%= link_to 'Edit', edit_logro_path(@logro) %> |
<%= link_to 'Back', logros_path %>